version: "3.7"
services:
  db:
    image: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: simpleApi
      MYSQL_ROOT_PASSWORD: secret
