version: "3.7"

volumes:
  mysql_data:

services:
  db:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: simpleApi
      MYSQL_ROOT_PASSWORD: secret
