name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: check out code into Go module directory
        uses: actions/checkout@v2

      - name: Get dependecies
        run: go mod download

      - name: Tests
        run: go test -v ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: check out code into Go module directory
        uses: actions/checkout@v2

      - name: Get dependecies
        run: go mod download

      - name: Build binary
        run: GOOS=linux GOARCH=amd64 go build -o application -ldflags="-s -w"
